pipeline {
  agent any

  stages {

    stage('Back-end') {
      steps {
        echo 'Starting Maven container...'
        sh 'docker run --name maven-container maven:3.8.1-adoptopenjdk-11 mvn --version'
        echo 'Maven container finished!'
      }
      post {
        always {
          echo 'Stopping and removing Maven container...'
          sh 'docker stop maven-container || false'
          sh 'docker rm   maven-container || false'
        }
      }
    }

    stage('Front-end') {
      steps {
        echo 'Starting Node container...'
        sh 'docker run --name node-container node:16-alpine node --version'
        echo 'Node container finished!'
      }
      post {
        always {
          echo 'Stopping and removing Node container...'
          sh 'docker stop node-container || false'
          sh 'docker rm   node-container || false'
        }
      }
    }

    stage('Clean Up Images') {
      steps {
        echo 'Removing Docker images...'
        sh 'docker rmi maven:3.8.1-adoptopenjdk-11 || false'
        sh 'docker rmi node:16-alpine || false'
        echo 'Images removed!'
      }
    }

  }

  post {
    success {
      echo 'Pipeline completed successfully!'
    }
    failure {
      echo 'Pipeline failed! Check logs.'
    }
    always {
      echo 'Pipeline done!'
    }
  }
}
